version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/srv/app/
    command: /srv/app/run_tests.sh
    environment:
      - GIT_COMMITTED_AT
      - CC_TEST_REPORTER_ID
